package md.ins8.steamspy.main

enum class NavigationEvent {
    HOME,
    ALL,
    TOP_2_WEEKS,
    TOP_OWNED,
    TOP_TOTAL,
    GENRE_ACTION,
    GENRE_STRATEGY,
    GENRE_RPG,
    GENRE_INDIE,
    GENRE_ADVENTURE,
    GENRE_SPORTS,
    GENRE_SIMULATION,
    GENRE_EARLY_ACCESS,
    GENRE_EX_EARLY_ACCESS,
    GENRE_MMO,
    GENRE_FREE,
    NOTIFICATIONS,
    SETTINGS,
    ABOUT
}
